#!/bin/sh

exec qemu-system-x86_64 -enable-kvm -m 1G \
  -boot c -hda /usr/local/vm/vm1.qcow2 \
  -monitor telnet:127.0.0.1:1234,server,nowait \
  -device nec-usb-xhci,id=usb,bus=pci.0 \
  -nographic \
#  -chardev socket,id=usbrdsocket,host=192.168.1.7,port=5555 \
#  -device usb-redir,chardev=usbrdsocket,id=redir0 -netdev bridge,id=hn1,br=br1 \
#  -device virtio-net-pci,netdev=hn1,id=nic0 \
