#!/bin/sh

exec qemu-system-x86_64 -enable-kvm -m 1G \
  -boot c -hda /usr/local/vm/vm0.qcow2 \
  -device pci-assign,host=00:14.0 -netdev bridge,id=hn0,br=br0 \
  -device virtio-net-pci,netdev=hn0,id=nic0 -nographic
